name             'opsinterview'
maintainer       'Art Witczak'
maintainer_email 'art.bikes@gmail.com'
license          'All rights reserved'
description      'Installs/Configures opsinterview'
long_description 'Installs/Configures opsinterview'
version          '0.1.0'
depends 'apt'
